# Logs

logs
_.log
npm-debug.log_

# Dependency directories

node_modules/

# Production build

dist/

# Tailwind CSS specific files

css/output.css

# Runtime data

pids
_.pid
_.seed
\*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover

lib-cov

# Coverage directory used by tools like istanbul

coverage
\*.lcov

# IDEs and editors

.idea/
.vscode/
\*.swp
.DS_Store

# Other files

.env
